### ISSUE TITLE
Keffiyeh reversed sprites

### ISSUE THREAD

**Issue by Gregormack** [Blackstone-SS13/BLACKSTONE#234] opened 2024-04-19 21:23 UTC
Issue reported from  Round ID: 8 (Blackstone (Rougetown on a Dedicated Server))

Reporting client version: 515.1636

Text:
Opened Keffiyeh looks like closed and vice versa

![image](https://github.com/Blackstone-SS13/BLACKSTONE/assets/65181932/eb5c4e02-b729-4ec6-9615-390976d23164)

**Comment by NGGJamie** [comment] 2024-04-22 05:05
Duplicate of #222

**Closed by NGGJamie** 2024-04-22 05:05 UTC
Labels: bug
