### ISSUE TITLE
Patron diety reverts to Astrata when you spawn

### ISSUE THREAD

**Issue by Wintermote** [Blackstone-SS13/BLACKSTONE#293] opened 2024-04-21 19:57 UTC
When you spawn as a cleric (maybe other classes?) with any diety besides Astrata or Necra as your patron diety, you will immediately be told you aren't pious enough to be a follower of Ravox/etc. and default back to Astrata.

Probably, we should grey out unselectable dieties rather than letting people pick one and then changing it on them when they spawn.

I do not know if these restrictions are due to whitelist flags or PQ requirements, but it'd be good to let players know in the character creator that their selections won't work, rather than when they spawn and can't change anything.

**Comment by NGGJamie** [comment] 2024-04-22 04:41
Duplicate of #292

**Closed by NGGJamie** 2024-04-22 04:41 UTC
