### ISSUE TITLE
[BUG] Wolves and spiders bite you all the time when you have 99% parry chance, despite successfully parrying them.

### ISSUE THREAD

**Issue by TonyKarsh** [Blackstone-SS13/BLACKSTONE#906] opened 2024-05-18 08:15 UTC
Issue reported from  Round ID: 349 (Blackstone (Rougetown on a Dedicated Server))

Reporting client version: 515.1636

I had a 99% parry chance for blocking wolves and spiders, and the messages said I blocked them successfully, but I still got bit, took armor damage and health damage every single time. The messages went like this:

Roll to parry with the halberd... 99%
Ashare ripostes the volf with the halberd!
The volf bites me! Armor stops the damage.
I wield the halberd normally.
Roll to parry with the halberd... 99%
Ashare ripostes the volf with the halberd!
The volf bites me!

![dreamseeker_xx1x0kHzTm](https://github.com/Blackstone-SS13/BLACKSTONE/assets/93961316/4a806d6b-a5f0-43d8-adc4-7d84299866d8)

**Comment by Sevaaas1** [comment] 2024-05-18 14:55
I’m in a bus right now and on my phone, so i cant check the code as i would like to, but from what i have seen so far i have a few theories

1. The proc for parrying doesn’t consider 99 as part of its interval ( unlikely, i remember parryng other players while i had 99% chance to parry )
2. The wrong proc is being called against simple mobs, it strikes me as odd that the text is “ X ripostes Y” afaik against players it says “X parries Y”
3. Volfs and beespiders have an attack speed that is higher than the CD for parry, if you could fight 1v1 against a volf while using the defend intent i would appreciate it ( it removes the delay between dodges and parries ), if this is the case then its not a bug

i will try to research some more, but since i wont have a Windows computer this weekend i wont be able to do any tests

**Comment by LucaNotLucas** [comment] 2024-05-18 15:41
> 2. The wrong proc is being called against simple mobs, it strikes me as odd that the text is “ X ripostes Y” afaik against players it says “X parries Y”

The text is "X ripostes Y" because he's on defend intent, with any other intent it says "parries" like you say, but while on defense it says "ripostes"

> 3. Volfs and beespiders have an attack speed that is higher than the CD for parry, if you could fight 1v1 against a volf while using the defend intent i would appreciate it ( it removes the delay between dodges and parries ), if this is the case then its not a bug

Like i said before, he IS on defense mode, so that's not the problem, not only that but if the CD for parrying was the problem, the "ripostes the volf" message wouldn't appear, as he wouldn't have blocked it on the first place because of the CD

**Comment by Bakeun0** [comment] 2024-05-18 16:25
The problem is that it's only checking to see if the user is from mob/living/carbon/human. Otherwise it just returns NULL

The checkdefense proc doesn't seem to stop damage even if it returns as true. I'm still not entirely sure what prevents damage being taken even after finding out problem was.

**Comment by ChungusGamer666** [comment] 2024-05-18 16:48
duplicate of existing issue althoughbeit

**Closed by ChungusGamer666** 2024-05-18 16:48 UTC
Labels: bug, good first issue, confirmed
